# Generated by Django 4.2.6 on 2023-11-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkapp', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='billing_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='shipping_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
